markdown: rdiscount
permalink: /:title/
url: http://github.thinkingbar.com
highlighter: pygments
name: 飘过的小牛
author: niushuai
email: hnns1990@gmail.com
duoshuo: niushuai
weibo: 1891858481
hub: niushuai
safe: true
paginate: 100
about: "弱菜一枚。"
